### ISSUE TITLE
add docker support

### ISSUE THREAD

**Issue by yashvardhan-kukreja** [yashvardhan-kukreja/nail-hacktoberfest#1]
**Is your feature request related to a problem? Please describe.**
This feature will make things convenient both on the end user's side and testing's side.

**Describe the solution you'd like**
Rightful dockerfile should be added so as to be able to build an image of this project which can be useful for multiple things and isolation. Users won't need to install nodejs or npm. They would just need to have docker and that's it.

**Describe alternatives you've considered**
NA

**Additional context**

**Comment by popey456963** [comment]
I would like to take a look at this issue, if possible.

**Comment by yashvardhan-kukreja** [comment]
@r-ush, thanks for your PR but I already merged a different PR of yours dealing with gitattributes. Also, seems like @popey456963 made the PR and asked for assignment prior to your PR, so, it would be more apt to go with their PR.

Still thanks for your work and please feel absolutely free to raise new issue or pick up any other existing issue😄
