### ISSUE TITLE
add support for CI testing on every push to the codebase

### ISSUE THREAD

**Issue by yashvardhan-kukreja** [yashvardhan-kukreja/nail-hacktoberfest#2]
**Is your feature request related to a problem? Please describe.**
Currently, the project does not have support to test whether the code it contains will successfully run or not. That might lead to exposure to potential human-prone issues.

**Describe the solution you'd like**
Add TravisCI/CircleCI or in general, any CI's testinig support so that, every push will only succeed when the code corresponding to the push passes a certain of tests successfully.

**Describe alternatives you've considered**
NA

**Additional context**
NA.

**Comment by DarthBenro008** [comment]
@yashvardhan-kukreja can we use GitHub Action to make this simpler? If so, I would like to take up this issue.

**Comment by yashvardhan-kukreja** [comment]
> @yashvardhan-kukreja can we use GitHub Action to make this simpler? If so, I would like to take up this issue.

of course, any CI mechanism would work. I had put up travis/circleci just for the sake of exemplifying.

Sure, go ahead with working on this 🤟
