### ISSUE TITLE
add a new fact

### ISSUE THREAD

**Issue by yashvardhan-kukreja** [yashvardhan-kukreja/nail-hacktoberfest#4]
**Is your feature request related to a problem? Please describe.**
NA

**Describe the solution you'd like**
Fact - The first computer virus was created in 1963.

**Describe alternatives you've considered**
NA

**Additional context**
NA

**Comment by AayushMehta169** [comment]
Can I be assigned this task?

**Comment by yashvardhan-kukreja** [comment]
sure @AayushMehta169 go ahead 😄
