### ISSUE TITLE
add linting

### ISSUE THREAD

**Issue by yashvardhan-kukreja** [yashvardhan-kukreja/nail-hacktoberfest#5]
**Is your feature request related to a problem? Please describe.**
Code pushed by different different people might have different styles/formats of coding. So, a way to make the code format in a uniform way across all commits.

**Describe the solution you'd like**
Add a linter to the code along side CI so that after every push the code get linted.  (checkout ESling)

**Describe alternatives you've considered**
NA

**Additional context**
NA

**Comment by vfreitas-** [comment]
I'll take this one 😄

**Comment by yashvardhan-kukreja** [comment]
nice job @vfreitas-  😄
